language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
script:
  - coverage run --source=nicoclient/ test_runner.py
after_success:
  - coveralls

# rm -rf dist/* build/* *.egg-info/*
# python3 setup.py sdist bdist_wheel
# python3 -m twine upload dist/*
