language: python
dist: xenial
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
script:
  - coverage run --source=nico_client/ test_runner.py
after_success:
  - coveralls
